### ISSUE TITLE
Code difference is getting more  between ggml and rwkv.cpp

### ISSUE THREAD

**Issue by yorkzero831** [saharNooby/rwkv.cpp#25]
Hi, 
I am working on rwkv-rs project which based on ggml as well, recentlly I am refering your implemtation of ggml, but I found it was hard to keep the rust friendly type defination (which is on master branch of gglm) and Q4_1_0 support (on your  master branch) together.

Do you have any plain to update your gglm or contribute the Q4_1_0  back to ggml?

Currently I manually merged part of your code (without Q4_1_0 ) with newest gglm code on my project.
and here is my project, 
https://github.com/yorkzero831/rwkv-rs

**Comment by saharNooby** [comment]
That's a diffucult situation.

On the one hand, I would like to keep `ggml` up to date, maybe even as a subrepo (so I don't need to manually pull updates). That way we get all new performance improvements and fixes for free.

On the other hand, ggml's `Q4_0` and `Q4_1` completely break RWKV, and we need `Q4_1_O` for any hope of quality; and both options "port `Q4_1_O` again every time ggml updates" and "just delete `Q4_1_O`" look very bad.

I guess my plan/vision currently is "it works fine now, so we can live without `ggml` updates at all".

I'll ask in `ggml` repo what they think about merging `Q4_1_O` upstream. I think they say something like "this is too specific and unoptimiized", but let's see.

**Comment by saharNooby** [comment]
I started the refactoring in [ggml-to-submodule](https://github.com/saharNooby/rwkv.cpp/tree/ggml-to-submodule) branch.

When merged, this will update `ggml` in `rwkv.cpp` to the latest version. After that, I would need to manually pull changes into the submodule to update `ggml`, but since there is now no new operators and change set is greatly reduced, this would be way easier.

Ideally, [I need to pull](https://github.com/ggerganov/ggml/issues/89) `Q4_1_O` format into upstream `ggml`. That way, I would not even need to support a `ggml` fork. As an alternative, vanilla `ggml` quantization formats may become good enough for RWKV, as mentioned in that issue.

**Comment by saharNooby** [comment]
@yorkzero831 I've forked most recent version of `ggml` [here](https://github.com/saharNooby/ggml). The fork contains [only one important commit](https://github.com/saharNooby/ggml/commit/4856b5d30a8985cde31efe4a5bfcc77ac1df61a6): introduction of `Q4_1_O` format. I guess it should be usable with Rust now.

**Comment by york-yu-ctw** [comment]
@saharNooby Really nice, it helps alot

**Comment by yorkzero831** [comment]
@saharNooby Really nice, that helps alot
